dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

install:
  - export CXX="g++-7" CC="gcc-7";

script:
- g++-7 --version
- cd buildtools
- make -f Makefile.linux CXX=g++-7 FLAGS=-std=c++11
