dist: bionic
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
      key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
    - gcc-5
    - g++-5
    - libcurl4-openssl-dev

before_install:
  #travis ci has it's own version of cmake that we need to replace
  - sudo apt-get remove cmake
  - sudo apt-get install cmake

install:
  - export CXX="g++-5" CC="gcc-5";

script:
- g++-5 --version
- cd buildtools
- cmake --version
- cmake .. -DSLEEPY_DISCORD_BUILD_EXAMPLES=1
- make
