dist: bionic
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ppa:hnakamur/cmake
    packages:
    - gcc-5
    - g++-5
    - libcurl4-openssl-dev
    - cmake

before_install:
  - curl -sSL https://github.com/Kitware/CMake/releases/download/v3.18.3/cmake-3.18.3-Linux-x86_64.sh --output cmake-script.sh
  - echo -e "ffy\ny\n" | bash cmake-script.sh

install:
  - export CXX="g++-5" CC="gcc-5";

script:
- g++-5 --version
- cd buildtools
- cmake .. -DSLEEPY_DISCORD_BUILD_EXAMPLES=1
- make
