dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

script:
- cd buildtools
- make -f Makefile.linux FLAGS=-std=c++11
