dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

install:
  - export CXX="g++-5" CC="gcc-5";

script:
- "$CXX" --version
- cd buildtools
- make -f Makefile.linux CXX=g++-5 FLAGS=-std=c++11
