# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#Do both 32 bit and 64 bit

- script: |
    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    .\bootstrap-vcpkg.bat
    cd
  displayName: 'vcpkg setup'

- script: |
    cd vcpkg
    .\vcpkg install openssl-windows:x86-windows-static
  displayName: 'OpenSSL Install'

- task: CMake@1
  inputs:
    CMakeArgs: .. -DBUILD_SLEEPY_DISCORD_EXAMPLES=1 -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL" -DOPENSSL_LIBRARIES="C:\Program Files\OpenSSL\lib"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'